# Site settings
title: Stockport Suicide Prevention
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stockport.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

prose:
  ignore: [".editorconfig", ".gitignore", "_config.yml", "README.md", "/_sass", "/_layouts", "/assets/lib", "/assets/css"]
  siteurl: "http://stockport.github.io"
  media: "assets/img"
