# Site settings
title: Stockport Suicide Prevention
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stockport.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

prose:
  ignore: [".editorconfig", ".gitignore", "_config.yml", "README.md", "/_sass"]
  siteurl: "http://stockport.github.io"
  media: "assets/img"
